/***************************************************************************//**
* File Name: cycfg_gatt_db.h
* Version: 1.1
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 1.1.0 build 291
*
********************************************************************************
* Copyright 2019 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS                0x1800u
#define __UUID_CHARACTERISTIC_DEVICE_NAME            0x2A00u
#define __UUID_CHARACTERISTIC_APPEARANCE             0x2A01u
#define __UUID_SERVICE_GENERIC_ATTRIBUTE             0x1801u
#define __UUID_SERVICE_GREENHOUSE_VALUES             0x65u, 0x63u, 0xD5u, 0xCFu, 0x3Au, 0x5Du, 0xDBu, 0x8Du, 0x36u, 0x41u, 0xF6u, 0xE0u, 0x74u, 0xE2u, 0xA0u, 0x31u
#define __UUID_CHARACTERISTIC_GREENHOUSE_VALUES_VALUE_TEMPERATURE    0x57u, 0x8Du, 0x43u, 0xD4u, 0xECu, 0x21u, 0x5Du, 0xA1u, 0x40u, 0x44u, 0x84u, 0x06u, 0x47u, 0xE8u, 0x02u, 0x23u
#define __UUID_CHARACTERISTIC_GREENHOUSE_VALUES_VALUE_LIGHT    0x1Au, 0x01u, 0x64u, 0x5Bu, 0x9Cu, 0x4Bu, 0xECu, 0xBAu, 0x98u, 0x4Bu, 0x56u, 0x44u, 0x41u, 0x19u, 0x27u, 0xEDu
#define __UUID_SERVICE_GREENHOUSE_TARGET             0xA5u, 0x8Bu, 0x92u, 0x6Bu, 0x7Au, 0x8Bu, 0x9Du, 0xB1u, 0x12u, 0x4Bu, 0x47u, 0x85u, 0x2Cu, 0x29u, 0xCBu, 0xB9u
#define __UUID_CHARACTERISTIC_GREENHOUSE_TARGET_TARGET_TEMPERATURE    0xD1u, 0x7Au, 0xBDu, 0x5Cu, 0x46u, 0xEBu, 0x6Bu, 0xBAu, 0xEFu, 0x48u, 0x71u, 0x2Bu, 0x38u, 0xC5u, 0x8Cu, 0x51u
#define __UUID_CHARACTERISTIC_GREENHOUSE_TARGET_TARGET_LIGHT    0xE2u, 0x8Bu, 0x88u, 0xB7u, 0x6Fu, 0xD3u, 0xE2u, 0xA9u, 0xC7u, 0x46u, 0x63u, 0xC7u, 0xA2u, 0x61u, 0x2Du, 0x77u

/* Service Generic Access */
#define HDLS_GAP                                     0x0001u
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                         0x0002u
#define HDLC_GAP_DEVICE_NAME_VALUE                   0x0003u
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                          0x0004u
#define HDLC_GAP_APPEARANCE_VALUE                    0x0005u

/* Service Generic Attribute */
#define HDLS_GATT                                    0x0006u

/* Service Greenhouse_Values */
#define HDLS_GREENHOUSE_VALUES                       0x0007u
/* Characteristic Value_Temperature */
#define HDLC_GREENHOUSE_VALUES_VALUE_TEMPERATURE     0x0008u
#define HDLC_GREENHOUSE_VALUES_VALUE_TEMPERATURE_VALUE    0x0009u
/* Characteristic Value_Light */
#define HDLC_GREENHOUSE_VALUES_VALUE_LIGHT           0x000Au
#define HDLC_GREENHOUSE_VALUES_VALUE_LIGHT_VALUE     0x000Bu

/* Service Greenhouse_Target */
#define HDLS_GREENHOUSE_TARGET                       0x000Cu
/* Characteristic Target_Temperature */
#define HDLC_GREENHOUSE_TARGET_TARGET_TEMPERATURE    0x000Du
#define HDLC_GREENHOUSE_TARGET_TARGET_TEMPERATURE_VALUE    0x000Eu
/* Characteristic Target_Light */
#define HDLC_GREENHOUSE_TARGET_TARGET_LIGHT          0x000Fu
#define HDLC_GREENHOUSE_TARGET_TARGET_LIGHT_VALUE    0x0010u

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_greenhouse_values_value_temperature[];
extern const uint16_t app_greenhouse_values_value_temperature_len;
extern uint8_t app_greenhouse_values_value_light[];
extern const uint16_t app_greenhouse_values_value_light_len;
extern uint8_t app_greenhouse_target_target_temperature[];
extern const uint16_t app_greenhouse_target_target_temperature_len;
extern uint8_t app_greenhouse_target_target_light[];
extern const uint16_t app_greenhouse_target_target_light_len;

#endif /* CYCFG_GATT_DB_H */

